name: main

on:
  push:
    branches:
      - master
      - main
      - default
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Typecheck
        uses: ./
      - name: Typecheck projectFixtures/sub
        uses: ./
        with:
          project: projectFixtures/sub
  publish:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/default'
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: 12.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: Install
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: yarn install
    - name: Build
      uses: tool3/ncc@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        src: 'src/index.ts'
        branch: release
