name: Release

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Restore dependencies
        id: cache-modules
        uses: actions/checkout@v2
        with:
          path: node_modules
          key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Install dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Build
        run: npm run build
      - Release
        uses: JasonEtco/build-and-tag-action@v1
        with:
          setup: ''
        env:
          GITHUB_TOKEN: ${{ github.token }}
